import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Youapp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        ></meta>
        <meta name="theme-color" content="#09141A"></meta>
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        ></meta>
      </head>
      <body className={inter.className}>
        <main className="fixed inset-0 bg-[#1E1E1E] flex flex-col items-center justify-center">
          <div className="relative transition-all duration-300 my-0 md:my-10 w-full h-full max-w-full md:max-w-sm max-h-full sm:max-h-[768px] mx-auto rounded-none sm:rounded-3xl overflow-hidden bg-main-gradient">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
